const path = require("path");

module.exports = {
  apps: [
    {
      name: "rmit-api",
      cwd: path.resolve(__dirname, "api"),
      script: "dist/src/main.js",
      instances: process.env.PM2_API_INSTANCES || 2,
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      kill_timeout: 5000,
      listen_timeout: 10000,
      restart_delay: 1000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      error_file: path.resolve(__dirname, "logs/api-error.log"),
      out_file: path.resolve(__dirname, "logs/api-out.log"),
      merge_logs: true,
      time: true,
      node_args: "--max-old-space-size=1024",
      env: {
        NODE_ENV: "production",
        PORT: 5000,
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 5000,
      },
      env_development: {
        NODE_ENV: "development",
        PORT: 5000,
      },
    },
    {
      name: "rmit-platform",
      cwd: path.resolve(__dirname, "platform"),
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000",
      instances: process.env.PM2_PLATFORM_INSTANCES || 2,
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      kill_timeout: 5000,
      listen_timeout: 10000,
      restart_delay: 1000,
      exp_backoff_restart_delay: 100,
      max_restarts: 15,
      error_file: path.resolve(__dirname, "logs/platform-error.log"),
      out_file: path.resolve(__dirname, "logs/platform-out.log"),
      merge_logs: true,
      time: true,
      node_args: "--max-old-space-size=1024",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      env_development: {
        NODE_ENV: "development",
        PORT: 3000,
      },
    },
  ],
};
